# Generated by Django 5.2.4 on 2025-07-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
