# Generated by Django 5.2.4 on 2025-07-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
