# Generated by Django 4.2.18 on 2025-01-29 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pros/')),
                ('added_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('choices', models.CharField(choices=[('LT', 'LEFT'), ('MD', 'MIDDLE'), ('RT', 'RIGHT')], max_length=2)),
            ],
        ),
    ]
