# Generated by Django 4.2.18 on 2025-05-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=62)),
                ('destination', models.CharField(max_length=62)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
