# Generated by Django 4.2.18 on 2025-05-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passangers'),
    ]

    operations = [
        migrations.AddField(
            model_name='passangers',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='passangers', to='flights.flights'),
        ),
    ]
