# Generated by Django 4.2.18 on 2025-02-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TododItems',
            new_name='TodoItems',
        ),
    ]
